### ISSUE TITLE
visual bug when user downloads a game directly 

### ISSUE THREAD

**Issue by GamerROMInc** [bucanero/pkgi-ps3#112] opened 2022-06-15 02:49 UTC
i have received reports of users receiving a visual bug that impacts the download progress bar, but seems to still download just fine https://i.redd.it/yd6m2f4onw491.jpg though this isn't a consistent bug it does happen from time to time

**Comment by bucanero** [comment] 2022-06-15 06:01
This was mentioned in #99 .  I still don't see a way to reproduce it. Does it happens with new downloads, or only when doing a resume download?

I have started and resumed a download a few times without problems. Even different urls, using http or ftp links and it works as expected.

I'd need to have a proper way to reproduce the issue before I can look on how to fix it.

**Comment by GamerROMInc** [comment] 2022-06-15 06:29
it happens when you're downloading some games normally the more you download games directly the more you will see it, I've had it happen to me once or twice after downloading a game directly i built a Pkgi Store version of yours you can try out yourself most people see it when they try to download a ps2 classics game directly using the same code you provided do you want a link to the modded version of PKGi?

**Comment by GamerROMInc** [comment] 2022-08-21 19:42
So here is an update: im assuming its a memory usage issue when transitioning from one app to another i had one report to me when i asked what he was doing before it happened: 

"I was just watching yt on my ps3 and decided "You know what I wanna play og2" and after waiting the 3 hrs it said this happens (i looked it up and it would take 153,150 years to finish that)"


So im assuming it happens when someone uses a app then either opens pkgi to quit there current app there in to pkgi witch is probably filling the ram up and pkgi not freeing up the ram or reserving ram to run efficiently.

**Comment by bucanero** [comment] 2022-08-21 21:24
duplicate of #99

**Closed by bucanero** 2022-08-21 21:24 UTC
